import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";
import "swiper/css";
import "swiper/css/effect-cards";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-full w-full antialiased`}
      >
        <div className="relative flex h-full w-full flex-col overflow-hidden border-4 border-blue-500">
          <header className="relative z-10 mx-auto flex h-[70px] min-h-[70px] w-screen max-w-[1440px] items-center justify-between border-b px-4">
            <Link href="/">
              <h2 className="text-base font-bold sm:text-2xl">
                Real Estate Portfolio
              </h2>
            </Link>
          </header>
          <main className="relative z-10 flex w-full flex-1 flex-col overflow-hidden">
            {children}
          </main>
          <div className="absolute left-0 top-0 -z-10 h-full w-full animate-[spin_8200ms_linear_infinite]">
            <div className="absolute left-[40%] top-[50%] h-[250px] w-[550px] -translate-x-[50%] -translate-y-[50%] bg-[#C9E9D2] blur-3xl"></div>
            <div className="absolute left-[60%] top-[50%] h-[550px] w-[250px] -translate-x-[50%] -translate-y-[50%] bg-[#FFE3E3] blur-3xl"></div>
            <div className="absolute left-[20%] top-[50%] h-[60vh] w-[60vh] -translate-x-[50%] -translate-y-[50%] rounded-full bg-[#D4BEE4] blur-3xl"></div>
          </div>
        </div>
      </body>
    </html>
  );
}
